SUGGESTED_INSIGHTS = [
    {"category": "pain", "label": "Pagar más de lo que te cotizaron", "description": "Te dan un precio inicial atractivo y al final la factura llega con cargos que nadie te mencionó. Sales perdiendo dinero que no tenías presupuestado."},
    {"category": "pain", "label": "Sobrecostos ocultos al final del envío", "description": "Aranceles, comisiones, manejo, almacenaje — aparecen cargos uno tras otro hasta destruir tu margen."},
    {"category": "pain", "label": "Pagar varios envíos por compras en distintas tiendas", "description": "Compras en 3 tiendas y pagas 3 envíos separados. El total te duele más que las compras mismas."},
    {"category": "pain", "label": "Impuestos inesperados al recibir la mercancía", "description": "Pensaste que ya estaba todo cubierto y al final te cobran IVA, ISR o aranceles extra que no calculaste."},
    {"category": "pain", "label": "Aranceles más altos de lo esperado", "description": "El producto entró a una categoría arancelaria que no preveías y terminas pagando 20% o 30% más."},
    {"category": "pain", "label": "Costos de almacenaje por retrasos", "description": "Tu paquete se atora en aduana o en bodega y te empiezan a cobrar por día de almacenaje sin avisarte."},
    {"category": "pain", "label": "Honorarios aduanales no contemplados", "description": "El agente aduanal cobra una tarifa que nadie te mencionó al cotizar."},
    {"category": "pain", "label": "Pérdida de rentabilidad por errores logísticos", "description": "Vendiste pensando en un costo, pero los gastos reales te dejaron en cero o en pérdida."},
    {"category": "pain", "label": "Clasificación arancelaria incorrecta que infló la factura", "description": "Un mal código pagó el doble de impuesto. Cuando te das cuenta, ya no puedes corregirlo sin pagar multa."},
    {"category": "pain", "label": "Paquetes detenidos en aduana sin explicación", "description": "Tu mercancía lleva días parada y nadie te dice por qué ni cuándo se libera."},
    {"category": "pain", "label": "Semanas de retraso por documentación incorrecta", "description": "Un papel mal llenado te cuesta dos semanas y tu cliente está esperando."},
    {"category": "pain", "label": "Quedarte sin inventario por retrasos", "description": "Tu cliente quiere comprar y no tienes producto. Pierdes la venta y la confianza."},
    {"category": "pain", "label": "Perder ventas por falta de mercancía a tiempo", "description": "El producto llega cuando ya pasó la temporada o el cliente compró con otro."},
    {"category": "pain", "label": "Invertir demasiado tiempo gestionando envíos", "description": "Pasas horas hablando con couriers, agentes y aduana en vez de vender."},
    {"category": "pain", "label": "No saber cuánto costará realmente la importación", "description": "Cotizas, pides, esperas — y solo hasta el final descubres el costo real."},
    {"category": "pain", "label": "No saber qué impuestos debes pagar", "description": "Cada producto tiene reglas distintas y nadie te las explica antes."},
    {"category": "pain", "label": "No saber dónde está tu paquete", "description": "Solo sabes que salió y que llegará algún día. Cero visibilidad del proceso."},
    {"category": "pain", "label": "No poder ver con foto cómo llegaron tus paquetes", "description": "Llega la mercancía y no sabes si está completa ni en qué estado, hasta que abres la caja."},
    {"category": "pain", "label": "Mercancía dañada al llegar", "description": "Compraste algo nuevo y llega golpeado, mojado o roto. Reclamar es otro problema."},
    {"category": "pain", "label": "Mercancía perdida en el trayecto", "description": "El paquete simplemente nunca llegó y nadie se hace responsable."},
    {"category": "pain", "label": "Aduana confiscó el envío", "description": "Por un permiso que no sabías que necesitabas, tu producto se queda allá. Y el dinero también."},
    {"category": "pain", "label": "Multas por errores en documentación", "description": "Un dato mal puesto y aduana te cobra una multa que nadie te advirtió."},
    {"category": "pain", "label": "Membresías mensuales que no pagas si no las usas", "description": "Te suscribes para tener PoBox y pagas mes a mes aunque no recibas nada."},
    {"category": "pain", "label": "Comisiones por valor de compras", "description": "Te cobran un porcentaje de lo que compras encima del envío. Mientras más compras, más pagas."},
    {"category": "pain", "label": "No poder hacer devoluciones desde México", "description": "Te llegó algo que no querías y devolverlo a USA es imposible o carísimo."},
    {"category": "pain", "label": "Mala comunicación del servicio de paquetería", "description": "No contestan, dan información contradictoria o desaparecen cuando hay un problema."},
    {"category": "pain", "label": "Retrasos sin explicación ni compensación", "description": "Tu envío se demora y la empresa solo dice 'aguanta'."},
    {"category": "pain", "label": "Tipo de cambio inflado sin avisar", "description": "Algunas empresas aplican un tipo de cambio peor que el real y se quedan con la diferencia."},
    {"category": "desire", "label": "Comprar en USA sin complicaciones", "description": "Quiere acceder a productos de Amazon, Walmart, Target o tiendas de marca como si estuviera allá."},
    {"category": "desire", "label": "Ahorrar en envíos consolidando paquetes", "description": "Sabe que puede juntar varias compras en un solo envío y ahorrar bastante. Lo quiere fácil."},
    {"category": "desire", "label": "Tener control total de sus compras desde su celular", "description": "Saber qué llegó, qué falta, qué pesa, cuándo se envía — todo en una app."},
    {"category": "desire", "label": "Recibir todo en México sin riesgos de aduana", "description": "Que alguien se encargue del papeleo y las gestiones y le entreguen la mercancía en su puerta."},
    {"category": "desire", "label": "Cotización completa y transparente desde el inicio", "description": "Saber el costo total antes de comprar, sin sorpresas al final."},
    {"category": "desire", "label": "Que alguien le diga si su producto se puede importar", "description": "Antes de gastar, quiere saber si su producto tiene restricciones o necesita permisos."},
    {"category": "desire", "label": "Crecer su negocio importando con seguridad", "description": "Importar volúmenes mayores sin que cada envío sea un dolor de cabeza."},
    {"category": "fear", "label": "Que el paquete nunca llegue", "description": "Pagar por algo que se pierde en el camino y nadie responda."},
    {"category": "fear", "label": "Ser estafado por una empresa de paquetería", "description": "Que se queden con su dinero o su mercancía y desaparezcan."},
    {"category": "fear", "label": "Pagar impuestos enormes que no calculó", "description": "Comprar pensando que iba a pagar X y terminar pagando el doble."},
    {"category": "fear", "label": "Perder mercancía valiosa por mal manejo", "description": "Que un producto frágil llegue destruido por descuido en la cadena."},
    {"category": "fear", "label": "Que aduana confisque su producto", "description": "Que su inversión termine en una bodega del gobierno sin posibilidad de recuperarla."},
    {"category": "fear", "label": "Quedar mal con sus clientes por retrasos", "description": "Prometer entregas y no cumplir porque el envío se atrasó."},
    {"category": "story", "label": "Cliente que ahorró consolidando 8 paquetes en un solo envío", "description": "Compró en Amazon, Walmart, Nike y 5 tiendas más. En vez de 8 envíos individuales, todo llegó junto. Ahorro del 60% en logística."},
    {"category": "story", "label": "Cliente que recuperó un paquete retenido en aduana", "description": "Lo que parecía perdido se liberó gracias a una corrección de documentación a tiempo. La mercancía salió y la venta se salvó."},
    {"category": "story", "label": "Error nuestro que asumimos sin pasar el costo al cliente", "description": "Uno de nuestro equipo cotizó mal una tarima. Cuando lo notamos, respetamos el precio original aunque significara pérdida. La confianza valía más que el costo."},
    {"category": "story", "label": "Cliente que dejó otra paquetería tras un mes esperando explicaciones", "description": "Llevaba 30 días sin saber dónde estaba su paquete. Llegó con nosotros, lo localizamos en 24 horas, y nunca volvió con la otra empresa."},
    {"category": "story", "label": "Cliente que escaló de comprar para sí mismo a abrir su tienda", "description": "Empezó importando productos personales. Hoy revende en Mercado Libre con margen porque sabe exactamente cuánto le cuesta cada cosa."},
]
